#!/bin/sh

export QTDIR=~/kde3.2-beta1
export KDEDIRS=~/kde3.2-beta1
export KDEHOME=~/.kde32

export LD_LIBRARY_PATH=~/kde3.2-beta1/lib
export PATH=~/kde3.2-beta1/bin:$PATH

startx ~/kde3.2-beta1/bin/startkde

# eof
