#!/usr/bin/perl -w
# vi: set ts=4 sw=4 :

use strict;

use Digest::SHA1 qw( sha1_hex );

for my $file (@ARGV)
{
	open(my $fh, "<", $file) or warn("open $file: $!\n"), next;
	my $data = do { local $/; <$fh> };
	my $hex = sha1_hex($data);
	print "$hex  $file\n";
}

# eof sha1sum
